package: community.lazycat.app.bentopdf
version: 2.8.8
name: BentoPDF
description: "The Privacy First PDF Toolkit"
min_os_version: 1.5.0
author: alam00000
license: AGPL-3.0-only
homepage: https://github.com/alam00000/bentopdf

permissions:
  required:
    - net.internet

locales:
  zh:
    name: "BentoPDF"
    description: "隐私优先的 PDF 工具箱"
  en:
    name: "BentoPDF"
    description: "The Privacy First PDF Toolkit"
